### PR TITLE
when vim launch, set to default im

### PR DESCRIPTION
**Pull request by xiehuc**

### CODE REVIEW

**Comment by xiehuc** [comment]
i use let g:barbaric_default = 0
but every launch vim, it doesn't set to default

something annoy

**Comment by rlue** [comment]
Have you tried updating to the most recent version of Barbaric? This problem was reported in issue #3, and has been fixed as of `2f7ab01`.

**Comment by xiehuc** [comment]
my branch was latest, and things differ with #3. 
i set g:barbar_default=0 in vimrc
my im switch to not english ( Rime method for example)
i open vim (or vimr)

but it didn't change to english. because it didn't have a chance to set to default

i think i could record a video to illustrate later

**Comment by xiehuc** [comment]
[untitle.mov.zip](https://github.com/rlue/vim-barbaric/files/1501245/untitle.mov.zip)

**Comment by rlue** [comment]
Oh, I see what you're talking about now.

Looks good, thanks!

**Pull request merged**
